### ISSUE TITLE
Clean actuary.go

### ISSUE THREAD

**Issue by diogomonica** [diogomonica/actuary#4]
Functions like `consoleOutput` and `jsonOutput`, etc, should be in an external file.

Also, the current code in `actuary.go` (in particular the `main()` method) should be under `cmd/actuary.go`. That is the go convention. The only things that should be in actuary.go should be our types (`Check`, `CheckResult`, etc)

/cc @zuBux

**Comment by zuBux** [comment]
Merging `checks` and `actuary` packages seems the right thing to do but there is a problem with the current structure. I'm not sure we actually need to have a `cmd/actuary.go`, since our project is not a library. Maybe we should consider a structure like this:

```
actuary/
    actuary.go    // package main
    profileutils/
    oututils/
    actuary/       //package actuary
        checks.go
        dockerfiles.go
        ....
```

`checks.go` will include all our types, functions while `actuary.go` will contain only the `main()` method

**Comment by diogomonica** [comment]
sounds good

**Comment by zuBux** [comment]
Should I merge the PR?

/cc @diogomonica

**Comment by diogomonica** [comment]
Yeah, LGTM
